version: '3.8'

services:
  # NestJS Application
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: my-nestjs-app-container
    volumes:
      - .:/app
      - /app/node_modules

  